### ISSUE TITLE
Chapter 3 - impossible to succeed with an excercise

### ISSUE THREAD

**Issue by freiondrej-lokalise** [PacktPublishing/Accelerating-Server-Side-Development-with-Fastify#56]
In `managing-the-routes-scope-nested.cjs`, the `parseUserHook()` sets isAdmin: true if level is 42. However, `level99Hook()` needs a level higher than 99, thus it's never possible to reach `/onlyAdmin` successfully. Or am I missing something? 

So maybe the condition in `parseUserHook` could be changed to e.g. `level === 100` so that it's possible to satisfy both conditions :)

**Comment by Eomm** [comment]
You don't miss anything! That's an error for sure!
Thanks for the report!
