### ISSUE TITLE
Mongo URL not being read

### ISSUE THREAD

**Issue by EnergeticPixels** [PacktPublishing/Accelerating-Server-Side-Development-with-Fastify#60]
Chapter 6, Section "Sharing the application configuration across plugins". I am getting an error message that says mongo URL is mandatory if no client provided.  I was following your book up to this point fairly well. Where did I go wrong?

This project has been transformed to ES6+ style of coding. Using NodeJS version 20 on a Debian 11 WSL (Windows 11 host).

Sample of my bug: https://github.com/EnergeticPixels/fastify_steroids/commit/9787c4ea4869f8425b16fa74fef8b455ebdbf3ee

**Comment by Eomm** [comment]
It should be a matter of wrong loading order.

In `app.js` atm, autoload is loading:

- plugins
- schemas
- configuration
- routes

This means that the `plugins/data-source.js` get `null` from `opts.mongo`.

You need to load the stuff in order:

- schemas
- configuration
- plugin
- routes

To get an example you may check the repository source code:
https://github.com/PacktPublishing/Accelerating-Server-Side-Development-with-Fastify/blob/main/Chapter%206/app.js (note that the configuration is a plugin in this case)

**Comment by EnergeticPixels** [comment]
@Eomm That did the trick. I also installed an all caps comment to remind myself -- ORDER IS IMPORTANT. Thank you.

Fixes #60.
